<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <Target Name="KillRunningApp" BeforeTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="taskkill /F /IM MVC.exe" ContinueOnError="true" IgnoreExitCode="true" />
  </Target>

</Project>
